name: squirrel
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython>=1.74
  - minimap2>=2.16
  - python>=3.7
  - snakemake-minimal
  - gofasta
  - iqtree>=2.1
  - cov-ert::jclusterfunk>=0.0.25
