name: squirrel
on: [push, pull_request]
defaults:
  run:
    shell: bash -l {0}

jobs:
  run_squirrel_test:
    name: squirrel test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          environment-file: environment.yml
          activate-environment: squirrel
          channels: conda-forge,bioconda,defaults
          miniforge-version: latest
      - name: Install squirrel
        run: pip install -e .
      - name: Check squirrel version
        run: squirrel --version
      - name: Run squirrel with test data
        run: squirrel squirrel/data/NC_063383.fasta 2>&1 | tee squirrel.log
      - name: Run squirrel phylo with test data
        run: squirrel squirrel/data/outgroups.fasta --run-phylo --outgroups 'KJ642615|Nigeria|1978' 2>&1 | tee squirrel_phylo.log
      - name: Run squirrel seq qc with test data
        run: squirrel squirrel/data/outgroups.fasta --run-phylo --outgroups 'KJ642615|Nigeria|1978' --seq-qc --assembly-refs squirrel/data/ref_seq.fasta 2>&1 | tee squirrel_qc.log
      