name: squirrel
on: [push, pull_request]
defaults:
  run:
    shell: bash -l {0}

jobs:
  run_squirrel_test:
    name: squirrel test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: squirrel
          channels: conda-forge,bioconda,defaults
          conda-version: "4.12.0"
          mamba-version: "*"
      - name: Install squirrel
        run: pip install -e .
      - name: Check squirrel version
        run: squirrel --version
      - name: Run squirrel with test data
        run: squirrel squirrel/data/NC_063383.fasta 2>&1 | tee squirrel.log
      